-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'
local function layout_bind(bind_table)
	return function()
		local workspace = hl.get_active_special_workspace() or hl.get_active_workspace()

		if not workspace then
			return
		end

		local layout = workspace.tiled_layout

		if bind_table[layout] then
			hl.dispatch(bind_table[layout])
		end
	end
end

-- ───────── My PERFECT Changes ─────────

hl.unbind("SUPER" .. " + " .. "TAB")
-- hl.unbind("SUPER" .. " + " .. "l")
-- hl.unbind("SUPER" .. " + " .. "h")
hl.unbind("SUPER + g")
hl.unbind("CTRL + ALT + tab")
hl.unbind("CTRL + SHIFT + tab")
hl.unbind("SUPER + E")
hl.unbind("SUPER + Q")
hl.unbind("SUPER + SPACE")
hl.unbind("SUPER + SHIFT" .. " + " .. "F")
hl.bind("SUPER + SHIFT + f", hl.dsp.window.fullscreen())
hl.bind("SUPER + CTRL + F", hl.dsp.window.fullscreen())
hl.bind("SUPER + CTRL + " .. 1, hl.dsp.window.move({ workspace = 1 }, { follow = false }))
hl.bind("SUPER + CTRL + " .. 2, hl.dsp.window.move({ workspace = 2 }, { follow = false }))
hl.bind("SUPER + CTRL + " .. 3, hl.dsp.window.move({ workspace = 3 }, { follow = false }))
hl.bind("SUPER + CTRL + " .. 4, hl.dsp.window.move({ workspace = 4 }, { follow = false }))
hl.bind("SUPER + CTRL + " .. 5, hl.dsp.window.move({ workspace = 5 }, { follow = false }))
hl.bind("SUPER + CTRL + " .. 6, hl.dsp.window.move({ workspace = 6 }, { follow = false }))
hl.bind("SUPER + CTRL + " .. 7, hl.dsp.window.move({ workspace = 7 }, { follow = false }))
hl.bind("SUPER + CTRL + " .. 8, hl.dsp.window.move({ workspace = 8 }, { follow = false }))
hl.bind("SUPER + CTRL + " .. 9, hl.dsp.window.move({ workspace = 9 }, { follow = false }))
hl.bind("SUPER + CTRL + " .. 0, hl.dsp.window.move({ workspace = 10 }, { follow = false }))
hl.bind("SUPER + q", hl.dsp.window.close())
hl.bind("SUPER + E", hl.dsp.exec_cmd("thunar"))
hl.bind("SUPER + SPACE", hl.dsp.window.float())
-- group
hl.bind("SUPER + G", hl.dsp.group.toggle())
-- Navigate within a group
-- bindd = CTRL, Tab, Change Group Forward, changegroupactive, f
hl.bind("CTRL+ALT + tab", hl.dsp.group.next({ forward = false }))
hl.bind("CTRL+SHIFT + Tab", hl.dsp.group.next({ forward = true }))

-- Desktop zooming or magnifier
hl.bind(
	"SUPER + ALT" .. " + " .. "mouse_down",
	hl.dsp.exec_cmd(
		"hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')"
	)
)

-- Scroll through existing workspaces with mainMod + scroll
hl.bind("SUPER" .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER" .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER" .. " + " .. "period", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER" .. " + " .. "comma", hl.dsp.focus({ workspace = "e-1" }))
-- hl.bind("CTRL_R", hl.dsp.exec_cmd("~/.config/hypr/scripts/Volume.sh --toggle-mic"))
hl.bind("SUPER + SHIFT" .. " + " .. "mouse:272", hl.dsp.exec_cmd("hyprpicker -a"))
hl.bind("SUPER + SHIFT" .. " + " .. "P", hl.dsp.window.pin())
hl.bind("SUPER" .. " + " .. "bracketleft", hl.dsp.exec_cmd("rofimoji --files math --action copy"))
hl.unbind("ALT_L" .. " + " .. "SHIFT_L")
hl.unbind("SHIFT_L" .. " + " .. "ALT_L")
-- hl.unbind("SUPER" .. " + " .. "H")
-- hl.bind("SUPER" .. " + " .. "l", hl.dsp.focus({ workspace = "+1" }))
-- hl.bind("SUPER" .. " + " .. "h", hl.dsp.focus({ workspace = -1 }))
-- hl.bind("SHIFT+SUPER" .. " + " .. "J", hl.dsp.layout("togglesplit"))
hl.bind("SUPER" .. " + " .. "tab", hl.dsp.focus({ workspace = "m+1" }))
hl.bind("SUPER + SHIFT" .. " + " .. "tab", hl.dsp.focus({ workspace = "m-1" }))
hl.bind("ALT" .. " + " .. "tab", hl.dsp.window.cycle_next())

hl.bind(
	"SHIFT+SUPER + J",
	layout_bind({
		scrolling = hl.dsp.layout("expel"), -- Scrolling: swap column with right one
		dwindle = hl.dsp.layout("togglesplit"), -- Dwindle: toggle window split
	})
)

-- TODO: manual review (unknown dispatcher: bring active to top)
-- hl.bind("ALT + tab", hl.dsp.bring active to top("bringactivetotop"))

-- ───────── Windowrules ─────────

-- hl.window_rule({
-- 	name = "workspace_3_silent",
-- 	match = {
-- 		match = { class = "^(Unity).*" },
-- 	},
-- 	workspace = "3",
-- })

hl.unbind("SUPER + A")

hl.bind("CTRL + code:105", hl.dsp.exec_cmd("/home/kukueb/.config/hypr/scripts/Volume.sh --toggle-mic"))

-- bind = SUPER, A, exec, qs -c /home/kukueb/Persona-Quickshell/ ipc call searchapp toggle

hl.bind("SUPER + ALT + mouse_down", function()
	local factor = hl.get_config("cursor.zoom_factor")
	if factor < 1 then
		factor = 1
	end
	hl.config({ cursor = { zoom_factor = factor * 2.0 } })
end)

hl.bind("SUPER + ALT + mouse_up", function()
	local factor = hl.get_config("cursor.zoom_factor")
	if factor < 1 then
		factor = 1
	end
	local new_factor = factor / 2.0
	if new_factor < 1 then
		new_factor = 1
	end
	hl.config({ cursor = { zoom_factor = new_factor } })
end)
